apiVersion: v1
kind: Pod
metadata:
  name: standard-storage
spec:
  containers:
  - image: cloudowski/fussy-container
    name: fussy
    volumeMounts:
      - mountPath: /data
        name: data1
  volumes:
    - name: data1
      persistentVolumeClaim:
        claimName: pvc-standard-storage

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-standard-storage
  labels:
    type: host
spec:
  # set to empty to disable dynamic provisioning using StorageClass
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
