apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: shoppinglists.cloudowski.com
spec:
  group: cloudowski.com
  versions:
    - name: v1beta1
      served: true
      storage: false
      schema:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                properties:
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        count:
                          type: integer
                      required:
                        - name
                        - count
                  store:
                    type: string
    - name: v1
      served: true
      storage: true
      schema:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                properties:
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        count:
                          type: integer
                      required:
                        - name
                        - count
                  store:
                    type: string
  conversion:
    strategy: None
  scope: Namespaced
  names:
    plural: shoppinglists
    singular: shoppinglist
    kind: ShoppingList
    shortNames:
    - sl
  preserveUnknownFields: false

