apiVersion: v1
kind: Service
metadata:
  labels:
    app: fussy-rs
  name: fussy-svc-nodeport
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: web
    nodePort: 30001
  selector:
    app: fussy-rs
