apiVersion: v1
kind: Pod
metadata:
  name: podvol
spec:
  containers:
  - image: busybox42/alpine-pod
    name: fussy
    volumeMounts:
    - mountPath: /data
      name: data1
    - mountPath: /shared
      name: shared
  volumes:
  - name: data1
    hostPath:
      path: /volumes/data1
  - name: shared
    nfs:
      server: 10.96.0.100
      path: "/vol7"
#    - name: data1
#      hostPath:
#        path: /volume/data1
#    - name: data2
#      persistentVolumeClaim:
#        claimName: pvc-data1
