---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsvol1
spec:
  storageClassName: "slow-but-stable"
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.96.0.100
    path: "/vol1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsvol2
spec:
  storageClassName: "slow-but-stable"
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.96.0.100
    path: "/vol2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsvol3
spec:
  storageClassName: "slow-but-stable"
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.96.0.100
    path: "/vol3"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsvol4
spec:
  storageClassName: "slow-but-stable"
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.96.0.100
    path: "/vol5"
