apiVersion: v1
kind: Pod
metadata:
  name: pvcvol-nfs
spec:
  containers:
  - image: busybox42/alpine-pod
    name: fussy
    volumeMounts:
    - mountPath: /data
      name: data2
  volumes:
  - name: data2
    persistentVolumeClaim:
      claimName: pvc-data3
